# -*- coding: utf-8 -*-
"""Calculadora básica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HdjUNpsMDN-UvvDyVKrcOuyGF_uEgXJs
"""

num1 = float(input("Digite o primeiro número: "))
num2 = float(input("Digite o segundo número: "))

while True:

    print("\nQual operação matemática deseja fazer?")
    print("1. Adição")
    print("2. Subtração")
    print("3. Multiplicação")
    print("4. Divisão")
    print("5. Sair")

    escolha = input("Digite o número da operação que deseja realizar: ")
    break

if escolha == '1':
    resultado = num1 + num2
    print(f"Resultado da adição: {resultado}")
elif escolha == '2':
    resultado = num1 - num2
    print(f"Resultado da subtração: {resultado}")
elif escolha == '3':
    resultado = num1 * num2
    print(f"Resultado da multiplicação: {resultado}")
elif escolha == '4':
    if num2 != 0:
        resultado = num1 / num2
        print(f"Resultado da divisão: {resultado}")
    else:
        print("Erro: Divisão por zero não é permitida.")
elif escolha == '5':
    print("Saindo do programa.")
else:
    print("Escolha inválida. Tente novamente.")
    #break  # This line was causing a syntax error outside of a loop